# Generated by Django 4.1 on 2023-10-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='height',
            field=models.FloatField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='wieght',
            field=models.FloatField(max_length=255, null=True),
        ),
    ]
