# Generated by Django 4.1 on 2023-10-12 00:03

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(default='user_icon.png', upload_to=main_app.models.user_directory_path),
        ),
    ]
